### ISSUE TITLE
For DINO-Mix model pretrained weight 

### ISSUE THREAD

**Issue by jinxxo-j** [GaoShuang98/DINO-Mix#1]
Hello! 
I'm interested in your paper, code.  
I want to use pretrained weight which you upload on baidu.
But, i can't login baidu.. 
Can you upload the pretrained weight file on github page?

**Comment by GaoShuang98** [comment]
We updated the readme file, added the google drive link of the best pretrained model "dino_vitb14".

**Comment by jinxxo-j** [comment]
Thank you!
