### ISSUE TITLE
GPU

### ISSUE THREAD

**Issue by libenchong** [GaoShuang98/DINO-Mix#2]
Hello, can your code run on an RTX 3090?

**Comment by GaoShuang98** [comment]
DINO-Mix在一张RTX4090上面是可以训练的，RTX3090没有试过，把batchsize调小一点应该是可以的。
DINO-Mix can be trained on a single RTX4090. RTX3090 hasn't tried it, so a smaller batchsize should do the trick.

**Comment by libenchong** [comment]
你好，vpr算是度量学习呀，里面的困难样本挖掘步骤应该是负样本的数量越多越好呀，要是把batchsize减小，训练效果会变差呀

**Comment by libenchong** [comment]
我在3090上按照你给的配置试了，batchsize=40，在pitts30ktest上R@1=0.9007，和你的结果差距有点大

**Comment by GaoShuang98** [comment]
再用main中的微调部分微调一下 (优化器改成adam)

**Comment by GaoShuang98** [comment]
效果变差也没办法呀，显存要大

**Comment by libenchong** [comment]
你的工作做的非常好，谢谢你的回答

**Comment by libenchong** [comment]
你好，能冒昧的问一下，论文表中的数据是你自己重新训的还是用的GSV-Citites数据集论文里面的数据呀，因为我看到在Norland数据集上的指标MixVPR是76.12，而在MixVPR原文中在Norland数据集上的R@是58.4呀，
